### ISSUE TITLE
File URL

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/preview#16]
Currently the URL is e.g.: https://preview.hex.pm/preview/decimal/2.0.0/lib%2Fdecimal%2Fcontext.ex

1. Do we need to escape the path?
2. Should we prefix the route, i.e. instead of `preview/decimal/2.0.0/lib/decimal/context.ex`, it's `preview/decimal/2.0.0/show/lib/decimal/context.ex`. This is to prevent conflicts where we'd want to add a route `preview/decimal/2.0.0/:something` which we couldn't as it could conflict with a path name. That being said, I don't know what :something would be. I suppose if need it, we could also add `:something/decimal/2.0.0` so it's probably a non-issue, but I thought I'd mention it anyway.

**Comment by ericmj** [comment]
1. I think it looks better if we don't escape, but I am not sure of what consequences of that are. Are there any security issues with not escaping?
2. We need to make sure we can add `preview/:organization/:package/:version/...` in the future so I think `/show/` is necessary to disambiguate. In hexdocs we solve a similar conflict by preventing docs with versions as root directories, but I don't think we should prevent general package tarballs from that.

**Comment by supersimple** [comment]
> Are there any security issues with not escaping?

**Comment by ericmj** [comment]
> I don't think so, but there is no ? to treat it as a parameter, so the router will (probably) go bonkers with a path that has extra / in it. I'm sure there are work-arounds for it.

Phoenix router supports globbing: `get "/foo/*filename"`

> maybe we just add hexpm in the path (as the org) now?

"hexpm" is optional almost everywhere else so I would like to avoid it if possible.
