### ISSUE TITLE
Default to displaying a more useful file

### ISSUE THREAD

**Issue by QuinnWilton** [hexpm/preview#17]
Right now, it looks like upon selecting a package, the lexicographically first file is displayed. For many projects, this will be a file like `.formatter.exs`: https://preview.hex.pm/preview/ecto/3.5.6/.formatter.exs

Perhaps it would be more useful to display a file that's more relevant to the goals of the project? One candidate would be `mix.exs`, since it's guaranteed to exist in all Mix projects, and also provides a good summary of the dependencies for the project.

**Comment by supersimple** [comment]
The order isn't lexicographical, they are sorted based on the order the tarball was built (the package value in ecto names .formatter.exs first.)
I am kind of opposed to considering any 1 file more relevant than any other in a project (especially when auditing.)
I am open to ideas on how we can order every package consistently.

**Comment by QuinnWilton** [comment]
Ah, got it! That makes sense then. Thanks for clarifying!

**Comment by ericmj** [comment]
I think we want some kind of a file tree browser [like on github](https://github.com/hexpm/preview/tree/main/lib) and [`T` file searcher](https://github.com/hexpm/preview/find/main) to make jumping between files easier. Defaulting to a README file or `mix.exs / rebar.config / Makefile` makes sense to me.

**Comment by supersimple** [comment]
For this issue, let's have the preview page look for these files (in this order) and the first one that exists will be the default page:
README (in any case and with or without an extension), mix.exs, rebar.config, Makefile. If none of those exist, use the first file in the package (current behaviour.)
