### ISSUE TITLE
Accessing a URL with a #LN does not highlight the given line

### ISSUE THREAD

**Issue by josevalim** [hexpm/preview#44]
For example, if you visit: https://preview.hex.pm/preview/ecto/3.6.1/show/lib/ecto/parameterized_type.ex#L11

The line won't be highlighted. Unfortunately, anchors are not send by browsers to the server, so there is no way to implement this functionality without JavaScript. In fact, my suggestion would be to move the whole implementation to JS, as there is already a hook and there is probably no need to ping the server for this functionality.

I would probably along these lines:

1. On [page-loading-stop](https://github.com/hexpm/preview/blob/main/assets/js/app.js#L37), see if there is an anchor, and if so, highlight the current line

2. Instead of phx-click, have the hook register a regular JavaScript click event that changes the anchor and highlights the current line

Also note the highlight is not changing accordingly when using the browser back and forward buttons. :)

Thank you! :heart:

**Comment by ericmj** [comment]
For me it works on the initial page loading: 
<img width="1113" alt="Screen Shot 2021-05-05 at 15 41 29" src="https://user-images.githubusercontent.com/316890/117150564-8ca2cf80-adb8-11eb-868b-4b38c89d46b8.png">

But when I come back to the page later the line is no longer highlighted, possibly after the load balancer has timed out the websocket connection and liveview has reloaded something maybe?

Seems like the best solution is to solve this in javascript 👍 .

**Comment by supersimple** [comment]
Thanks for documenting this @josevalim 
Just curious what OS/Browser you were using? It still needs to be fixed regardless.
What are your thoughts on using phx-hook to implement trigger the js highlight versus adding an onclick event directly in the DOM?

**Comment by josevalim** [comment]
Ah yes, I am using Firefox. :)

my thought was to use the hook and inside the hook register the onclick event :)

**Comment by supersimple** [comment]
> Ah yes, I am using Firefox. :)
ok, same here. I am on Ubuntu 20.04. I assume you are on MacOS.
I'll make sure I test it on my mac as well once I/we have a PR together.
